spring:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    properties:
      hibernate:
        show_sql: true
        #use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/web_2